---
title: "TD 1+2+3 'Enquête'"
author: "Bruno Fischer Colonimos, calculs de l'exercice 'Enquête'"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: 
    # html_document:
    #   toc: yes
    #   number_sections: yes
    pdf_document:
      toc: yes
      number_sections: yes
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, fig.width = 3, fig.align = "center", fig.show = "hold", fig.asp = 1)

library(dplyr)
library(ggplot2)
library(pander)

options(scipen = 2)
```

Data
=====

```{r dataget}
datadir <- "data"
fname <- "Donnees TD-3-Survey.csv"
fpath <- file.path(datadir, fname)
# file.exists(fpath)
df <- read.csv(fpath, sep = ";", stringsAsFactors = FALSE)
# names(df)

# fix the names(remove accents + fix revenu....)
names(df) <- tolower(iconv(names(df),to="ASCII//TRANSLIT"))
names(df)[6] <- "revenu"

# Eliminer les accents dans l'etablissement
df$etablissement <- iconv(df$etablissement,to="ASCII//TRANSLIT")

```

```{r dataclean}

# data cleaning
df$dept <- factor(df$dept)
df$sexe <- factor(df$sexe)
df$etablissement <- factor(gsub("Coll. ", "Coll ", df$etablissement))
```

Data, after cleaning (etablissement)

```{r datashow}
# kable(df)
pander(df)
# kable(summary(df))
panderOptions('missing', "") # empty strings instead of NA
pander(summary(df), justify = c('right', 'left', 'left', 'right', 'left', 'right'))
```




```{r anafun}
# make a table

maketable <- function(var, cum = FALSE, horiz = TRUE) {
        efftab <- table(var)
        effcum = cumsum(efftab)
        if (cum) {
                tab <-rbind(effectif = efftab,
                            frequence = prop.table(efftab),
                            eff.cum = effcum)
        } else {
                tab <-rbind(effectif = efftab,
                            frequence = prop.table(efftab))
        }
        htab <- as.data.frame(tab)
        return(if (horiz) {htab} else {t(htab)})
}

# summary

kbsummary <- function(var, horiz = TRUE, qtype = 2) {
        # population standard deviation
        sdpop <- function(x, ...) {
                n <- length(x)
                sqrt((n-1) / n) * sd(x, ...)
        }
        mysummary <- quantile(x = var, 
                              probs = c(0, .25, .5, .75, 1), 
                              na.rm = TRUE, type = qtype)
        names(mysummary) <- c("Min", "Q1", "Median", "Q3", "Max")
        
        moresummary <- sapply(list(Mean = function(z){mean(z, na.rm = TRUE)},
                                   Sd.pop = function(z){sdpop(z, na.rm = TRUE)},
                                   Sd = function(z){sd(z, na.rm = TRUE)} ), 
                              function(f){f(var)})
        tb <- as.array(c(mysummary, moresummary))
        if (horiz) {
                t(tb)
        } else {
                tb
        }
}


```





Variable par variable
=====================

age (quanti discrete)
----

Valeurs: `r pander(sort( unique(df$age)))`. Traitement comme variable discrète.

```{r age}
variable <- "age"
tablestyle <- "horiz" # "vert" or NA
cumtable <- TRUE
breakscontrol <- 6:14
horizontalsummary <- TRUE

```


```{r quantdis, warning=FALSE}
# table
if (!is.na(tablestyle)) {
        vtb <- kable(maketable(df[[variable]], 
                               cum = cumtable,
                               horiz = (tablestyle == "horiz")), 
                     digits = 3)
}


vs <- pander(kbsummary(var = df[[variable]], horizontalsummary)) # vs kable

# plots
p1 <- local({
  g <- ggplot(data = df, aes_string(variable)) + geom_bar(aes(y = ..prop..))
  if (is.na(breakscontrol)) {
    g
  } else {
    g + scale_x_continuous(breaks = breakscontrol)
  }
})

  
p2 <- ggplot(data = df, aes(x=1)) + 
  geom_boxplot(aes_string(y=variable)) + 
  scale_x_continuous("", breaks = NULL) +
  coord_flip()

```

```{r quantdis_show}
vtb
vs
p1
p2
```


departement (dept) (quali)
---------------------------

```{r dept}
variable <- "dept"
```

```{r quali}
# table
# kable(maketable(df[[variable]], horiz = TRUE))
pander(maketable(df[[variable]], horiz = TRUE))
# no summary
# plots
ggplot(data = df, aes_string(variable)) + geom_bar(aes(y = ..prop.., group = 1)) 

```


sexe (quali)
------------

```{r sexe}
variable <- "sexe"
```

```{r sexe2, ref.label = "quali"}
```


fratrie (quanti discrete)
-------------------------

```{r fratrie}
variable <- "fratrie"
breakscontrol <- NA
horizontalsummary <- TRUE
```

```{r frat2, ref.label = "quantdis"}
```

```{r frat3, ref.label = "quantdis_show"}
```


Etablissement (quali)
----------------------

Remarque: 

* Les données ont été nettoyées (originalement, on trouvait des valeurs `Coll ` et `Coll.`)
* potentiellement, ces données ne sont pas "tidy", puisque cette colonne regroupe 2 variables: niveau = {ecole / college}, et statut = {public / privé}


```{r etablissement}
variable <- "etablissement"
```

```{r etab2, ref.label = "quali"}
```


revenu (quanti continue)
------------------------

```{r revenu}
variable <- "revenu"
breakscontrol <- NA
binscontrol = nclass.Sturges(df[[variable]])
horizontalsummary <- TRUE
```

```{r quantcont}
# table
# vtb <- kable(maketable(df[[variable]], horiz = FALSE))

vs <- kable(kbsummary(var = df[[variable]], horizontalsummary))

# plots
p1 <- local({
  g <- ggplot(data = df, aes_string(variable)) + 
    geom_histogram(bins = binscontrol)
  if (is.na(breakscontrol)) {
    if (is.na(binscontrol)) {
      g
    } else {
      g #+ scale_x_continuous(bins = binscontrol)
    }
    
  } else {
    g #+ scale_x_continuous(breaks = breakscontrol)
  } 
})

p2 <- ggplot(data = df, aes(x=1)) + 
  geom_boxplot(aes_string(y=variable)) + 
  scale_x_continuous("", breaks = NULL) +
  coord_flip()

```

```{r quantcont_show}
# vtb
vs
p1
p2
```

