---
title: "test"
author: "Bruno Fischer Colonimos"
date: "1 mars 2019"

output:
  pdf_document:
      fig_caption: yes
  html_document: 
      fig_caption: yes
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pander)
library(tables)
```
table
------

--------------------------------------------------------
     aspect         1        2        3        4      5 
---------------- -------- -------- -------- -------- ---
     **n**          5        6        6        8      1 

  **Moyenne**      1.4       2      2.667    3.875    4 

 **Ecart-type**   0.8944   0.6325   0.8165   0.8345     
--------------------------------------------------------

Table: Statistiques de `gout`, pour chaque valeur de `aspect`



```{r test2, fig.cap="blah"}
pander(head(mtcars), caption = "thecaption")
```

```{r}
pander(head(mtcars[1:5], 3))
```

```{r}
pander(tabular( (Species + 1) ~ (n=1) + Format(digits=2)*
         (Sepal.Length + Sepal.Width)*(mean + sd), data=iris ))
```

```{r}
rm(Group)
rm(X)
dfr <- local({
        X <- rnorm(125, sd=100)
        Group <- factor(sample(letters[1:5], 125, rep=TRUE))
        Y <- rnorm(125, mean = 25 ,sd=10)
        data.frame(Group, X,Y)
})

# tab <- tabular( Group ~ (n=1)+Format(digits=2)*X*((Mean=mean) + Heading("Std Dev")*sd ))
tab <- tabular( Group ~ (n=1) + Format(digits=2)*(X + Y)*((Mean=mean) + (`Standard Deviation` = sd) ),
                data = dfr)
pander(tab)

```

```{r}

```

